FROM php:7.4-fpm

ARG user
ARG uid

RUN rm /etc/apt/preferences.d/no-debian-php
RUN apt update && \
    apt install -y apt-transport-https git php-mbstring php-gmp php-dom php-gd php-curl zip nano 
RUN docker-php-ext-install mysqli pdo_mysql

RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Composer <Installed locally for faster deploying purposes>
# RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Create system user to run Composer and Artisan Commands
# RUN useradd -G www-data,root -u $uid -d /home/$user $user
# RUN mkdir -p /home/$user/.composer && \
#     chown -R $user:$user /home/$user
RUN mkdir -p ~/.composer
RUN chown -R $user ~/.composer

WORKDIR /app

# COPY ./composer.json .
# COPY ./composer.lock .
COPY . .

USER $user
# RUN composer install --ignore-platform-reqs
RUN php artisan config:clear
RUN php artisan cache:clear
RUN php artisan key:generate
RUN php artisan storage:link
RUN php artisan passport:install

EXPOSE 8000
